In [22]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import MissingIndicator,SimpleImputer

In [23]:
df=pd.read_csv("C:/Users/Dell/Downloads/train.csv",usecols=['Age','Fare','Survived'])

In [24]:
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [25]:
x=df.drop(columns=['Survived'])
y=df['Survived']

In [26]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [27]:
X_train.head()

      Age     Fare
331  45.5  28.5000
733  23.0  13.0000
382  32.0   7.9250
704  26.0   7.8542
813   6.0  31.2750

In [28]:
si=SimpleImputer()
X_train_trf=si.fit_transform(X_train)
X_test_trf=si.transform(X_test)

In [29]:
from sklearn.linear_model import LogisticRegression
clf=LogisticRegression()
clf.fit(X_train_trf,y_train)
y_pred=clf.predict(X_test_trf)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6480446927374302

In [30]:
mi=MissingIndicator()
mi.fit(X_train)

MissingIndicator()

In [31]:
mi.features_

array([0])

In [32]:
X_train_missing=mi.transform(X_train)

In [33]:
X_test_missing=mi.transform(X_test)

In [34]:
X_train['Age_NA']=X_train_missing

In [35]:
X_test['Age_NA']=X_test_missing

In [36]:
X_train

      Age      Fare  Age_NA
331  45.5   28.5000   False
733  23.0   13.0000   False
382  32.0    7.9250   False
704  26.0    7.8542   False
813   6.0   31.2750   False
..    ...       ...     ...
106  21.0    7.6500   False
270   NaN   31.0000    True
860  41.0   14.1083   False
435  14.0  120.0000   False
102  21.0   77.2875   False

[712 rows x 3 columns]

In [37]:
si=SimpleImputer()
X_train_trf=si.fit_transform(X_train)
X_test_trf=si.transform(X_test)

In [38]:
from sklearn.linear_model import LogisticRegression
clf=LogisticRegression()
clf.fit(X_train_trf,y_train)
y_pred=clf.predict(X_test_trf)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6368715083798883