In [10]:
#DataFrame:It is like 2D array in which it looks like a table like structure
#and every column in DataFrame is series and row is also series

In [48]:
#using list
import pandas as pd
student_data=[
    [30,50,5],
    [40,40,4],
    [20,30,3]
]
students=pd.DataFrame(student_data,columns=['iq','marks','package'])

In [49]:
#using dict
student_dict={
    'iq':[100,90,80],
    'name':['P','Q','R'],
    'package':[3,5,6]
}
students=pd.DataFrame(student_dict)
students.set_index('name',inplace=True)

students.head()

       iq  package
name
P     100        3
Q      90        5
R      80        6

In [13]:
train=pd.read_csv("C:/Users/Dell/Downloads/train.csv")
train
ipl=pd.read_csv("C:/Users/Dell/Downloads/ipl-matches.csv")

In [14]:
placement=pd.read_csv("C:/Users/Dell/Downloads/placement.csv")
placement

    Unnamed: 0  cgpa     iq  placement
0            0   6.8  123.0          1
1            1   5.9  106.0          0
2            2   5.3  121.0          0
3            3   7.4  132.0          1
4            4   5.8  142.0          0
..         ...   ...    ...        ...
95          95   4.3  200.0          0
96          96   4.4   42.0          0
97          97   6.7  182.0          1
98          98   6.3  103.0          1
99          99   6.2  113.0          1

[100 rows x 4 columns]

# attributes and methods

In [15]:
#shape
placement.shape

(100, 4)

In [16]:
#dtypes
train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [17]:
#index
train.index

RangeIndex(start=0, stop=891, step=1)

In [18]:
#columns
train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [19]:
train.values

array([[1, 0, 3, ..., 7.25, nan, 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, nan, 'S'],
       ...,
       [889, 0, 3, ..., 23.45, nan, 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, nan, 'Q']], dtype=object)

In [20]:
train.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [21]:
train.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [22]:
train.sample(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
251,252,0,3,"Strom, Mrs. Wilhelm (Elna Matilda Persson)",female,29.0,1,1,347054,10.4625,G6,S
284,285,0,1,"Smith, Mr. Richard William",male,NaN,0,0,113056,26.0000,A19,S
447,448,1,1,"Seward, Mr. Frederic Kimber",male,34.0,0,0,113794,26.5500,NaN,S
233,234,1,3,"Asplund, Miss. Lillian Gertrud",female,5.0,4,2,347077,31.3875,NaN,S
478,479,0,3,"Karlsson, Mr. Nils August",male,22.0,0,0,350060,7.5208,NaN,S
647,648,1,1,"Simonius-Blumer, Col. Oberst Alfons",male,56.0,0,0,13213,35.5000,A26,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
77,78,0,3,"Moutal, Mr. Rahamin Haim",male,NaN,0,0,374746,8.0500,NaN,S
354,355,0,3,"Yousif, Mr. Wazli",male,NaN,0,0,2647,7.2250,NaN,C
186,187,1,3,"O'Brien, Mrs. Thomas (Johanna ""Hannah"" Godfrey)",female,NaN,1,0,370365,15.5000,NaN,Q

In [23]:
placement.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  100 non-null    int64
 1   cgpa        100 non-null    float64
 2   iq          100 non-null    float64
 3   placement   100 non-null    int64
dtypes: float64(2), int64(2)
memory usage: 3.3 KB

In [24]:
placement.describe()

       Unnamed: 0        cgpa          iq   placement
count  100.000000  100.000000  100.000000  100.000000
mean    49.500000    5.991000  123.580000    0.500000
std     29.011492    1.143634   39.944198    0.502519
min      0.000000    3.300000   37.000000    0.000000
25%     24.750000    5.075000  101.500000    0.000000
50%     49.500000    6.000000  127.500000    0.500000
75%     74.250000    6.900000  149.000000    1.000000
max     99.000000    8.500000  233.000000    1.000000

In [25]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [26]:
placement.duplicated() #it gives in boolean result it checks wether the row is duplicate or not

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Length: 100, dtype: bool

In [27]:
train.duplicated().sum()

np.int64(0)

In [28]:
#rename
train.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [29]:
#if we want to change name column like Pclass to Aclass and SEx to Gender 
train.rename(columns={
    'Pclass': 'Aclass',
    'Sex': 'Gender'
}, inplace=True) #inplace=true it gives permenent change
train.head()

,PassengerId,Survived,Aclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# maths functions

In [30]:
#train.sum()#it gives error beacuse it contains numrical and text values 
train.sum(numeric_only=True,axis=0) #if axis is 1 then rowwise sum if 0 then column wises

PassengerId    397386.0000
Survived          342.0000
Aclass           2057.0000
Age             21205.1700
SibSp             466.0000
Parch             340.0000
Fare            28693.9493
dtype: float64

In [31]:
placement.mean()

Unnamed: 0     49.500
cgpa            5.991
iq            123.580
placement       0.500
dtype: float64

In [32]:
placement.max()

Unnamed: 0     99.0
cgpa            8.5
iq            233.0
placement       1.0
dtype: float64

In [33]:
placement.min()

Unnamed: 0     0.0
cgpa           3.3
iq            37.0
placement      0.0
dtype: float64

In [34]:
placement.var()

Unnamed: 0     841.666667
cgpa             1.307898
iq            1595.538990
placement        0.252525
dtype: float64

In [35]:
placement.std()

Unnamed: 0    29.011492
cgpa           1.143634
iq            39.944198
placement      0.502519
dtype: float64

# fetching Columns

In [36]:
# if we want single column
train['Name']#it is also known as series

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [37]:
# for multiple columns
train[['PassengerId','Survived','Aclass']]

     PassengerId  Survived  Aclass
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

[891 rows x 3 columns]

# fetching multiple rows

In [38]:
#iloc :it fetches rows with help of index or position
train.iloc[0] # it gives first row

PassengerId                          1
Survived                             0
Aclass                               3
Name           Braund, Mr. Owen Harris
Gender                            male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [39]:
#for multiple rows
#if i want starting 5 rows
train.iloc[0:5]

,PassengerId,Survived,Aclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [40]:
#if i want rows from 5 to 15 and it should be alternate
train.iloc[5:16:2]

,PassengerId,Survived,Aclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S

In [41]:
#i want to all rows from 5 th row
train.iloc[5:]

,PassengerId,Survived,Aclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [42]:
#if i want 0,4,5 index rows
train.iloc[[0,4,5]]

,PassengerId,Survived,Aclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q

In [43]:
#loc:It fetches the row with help of label
students.loc['P']

iq         100
package      3
Name: P, dtype: int64

In [44]:
students.loc['P':'R']#here R is also included

       iq  package
name
P     100        3
Q      90        5
R      80        6

In [45]:
students.loc[['P','Q','R']]

       iq  package
name
P     100        3
Q      90        5
R      80        6

In [46]:
train.iloc[0:3,0:3]# it gives rows from 0 to 2 and columns from 0 to 2

   PassengerId  Survived  Aclass
0            1         0       3
1            2         1       1
2            3         1       3

In [82]:
ipl.sample(10)
ipl.shape

(950, 20)

In [56]:
#find all final winners
mask=ipl['MatchNumber']=='Final'
new_df=ipl[mask]
new_df[['Season','WinningTeam']]

      Season            WinningTeam
0       2022         Gujarat Titans
74      2021    Chennai Super Kings
134  2020/21         Mumbai Indians
194     2019         Mumbai Indians
254     2018    Chennai Super Kings
314     2017         Mumbai Indians
373     2016    Sunrisers Hyderabad
433     2015         Mumbai Indians
492     2014  Kolkata Knight Riders
552     2013         Mumbai Indians
628     2012  Kolkata Knight Riders
702     2011    Chennai Super Kings
775  2009/10    Chennai Super Kings
835     2009        Deccan Chargers
892  2007/08       Rajasthan Royals

In [59]:
#how many super over finishes have occured
super=ipl['SuperOver']=='Y'
super.sum()

np.int64(14)

In [71]:
#how many matches has csk won in kolkata
ipl[(ipl['City']=='Kolkata')&(ipl['WinningTeam']=='Chennai Super Kings')].shape

(5, 20)

In [83]:
#toss winner is match winner in percentage
win=ipl['TossWinner']==ipl['WinningTeam']
sum=win.sum()
avg=sum/950
avg*100

np.float64(51.473684210526315)

In [84]:
movies=pd.read_csv("C:/Users/Dell/Downloads/movies.csv")

In [95]:
movies.sample(10)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
618,Luv U Soniyo,tt2188811,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Luv_U_Soniyo,Luv U Soniyo,Luv U Soniyo,0,2012,144,Comedy|Romance,5.5,63,Mark & Soniyo who after having been brought t...,Mark & Soniyo after having been brought toget...,NaN,Tanuj Virwani|Neha Hinge|Bunty Grewal|Shobhit ...,NaN,26 July 2013 (India)
574,Main Krishna Hoon,tt1855268,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Main_Krishna_Hoon,Main Krishna Hoon,Main Krishna Hoon,0,2013,134,Animation|Family|Musical,5.5,159,An abandoned baby boy is rescued from floodwat...,An abandoned baby boy is rescued from floodwat...,Krishna from Earth Meets Krishna from Heaven,Juhi Chawla|Paresh Ganatra|Namit Shah|Katrina ...,NaN,25 January 2013 (India)
458,Jai Ho (film),tt1188982,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Jai_Ho_(film),Jai Ho,Jai Ho,0,2014,135,Action|Drama,5.2,15868,An ex-army officer initiates a unique idea of ...,An ex-army officer initiates a unique idea of ...,People's Man,Salman Khan|Daisy Shah|Tabu|Danny Denzongpa|Na...,1 win & 5 nominations,24 January 2014 (USA)
959,All the Best: Fun Begins,tt1433905,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/All_the_Best:_Fu...,All the Best: Fun Begins,All the Best: Fun Begins,0,2009,144,Action|Comedy|Drama,6.1,5100,Veer Kapoor lives in a palatial bungalow in Go...,The unexpected arrival of his elder NRI brothe...,NaN,Sanjay Dutt|Ajay Devgn|Fardeen Khan|Bipasha Ba...,2 wins & 2 nominations,16 October 2009 (India)
912,3 Idiots,tt1187043,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/3_Idiots,3 Idiots,3 Idiots,0,2009,170,Comedy|Drama,8.4,310481,Farhan Qureshi and Raju Rastogi want to re-uni...,Two friends are searching for their long lost ...,Don't be Stupid. Be an I.D.I.O.T.,Aamir Khan|Madhavan|Sharman Joshi|Kareena Kapo...,57 wins & 18 nominations,25 December 2009 (India)
665,Jodi Breakers,tt2191721,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Jodi_Breakers,Jodi Breakers,Jodi Breakers,0,2012,127,Comedy|Musical|Romance,3.5,1063,Sid and Sonali help people in getting divorce ...,Sid and Sonali help people in getting divorce ...,Single Rehne Ka Bejod Formula,Bipasha Basu|Helen|Pradeep Kharab|Madhavan|Tar...,NaN,24 February 2012 (USA)
183,Hotel Salvation,tt5997928,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Mukti_Bhawan,Hotel Salvation,Hotel Salvation,0,2016,102,Comedy|Drama,7.1,1487,Faced with his father's untimely and bizarre d...,Faced with his father's untimely and bizarre d...,NaN,Adil Hussain|Lalit Behl|Geetanjali Kulkarni|Pa...,15 wins & 6 nominations,7 April 2017 (India)
193,Hindi Medium,tt5764096,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Hindi_Medium_(film),Hindi Medium,Hindi Medium,0,2017,132,Comedy|Drama,7.8,18315,A couple from Chandni Chowk aspire to give the...,A couple from Chandni Chowk aspire to give the...,NaN,Irrfan Khan|Saba Qamar|Dishita Sehgal|Deepak D...,6 wins & 15 nominations,19 May 2017 (USA)
421,Aisa Yeh Jahaan,tt4760900,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Aisa_Yeh_Jahaan,The World It Is,Aisa Yeh Jahaan,0,2015,120,Drama,7.0,42,The film is set in Mumbai. It depicts the rela...,During a vacation with her parents away from ...,NaN,Yashpal Sharma|Ira Dubey|Tinnu Anand|Palash Sen|,2 nominations,24 July 2015 (India)
564,Badlapur Boys,tt2767712,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Badlapur_Boys,Badlapur Boys,Badlapur Boys,0,2014,123,Drama,4.7,113,A story about a bunch of underdogs who not onl...,A story about a bunch of underdogs who not onl...,NaN,Annu Kapoor|Anupam Maanav|Saranya Mohan|Nishan...,NaN,12 December 2014 (India)

In [93]:
#movies with rating higher than 8 and votes>10000
movies[(movies['imdb_rating']>8)&(movies['imdb_votes']>10000)].shape

(43, 18)

In [94]:
#action movies with rating higher than 7.5

movies[(movies['genres']=='Action')&(movies['imdb_rating']>7.5)].shape

(0, 18)

In [96]:
movies['country']='India'

In [97]:
movies.columns

Index(['title_x', 'imdb_id', 'poster_path', 'wiki_link', 'title_y',
       'original_title', 'is_adult', 'year_of_release', 'runtime', 'genres',
       'imdb_rating', 'imdb_votes', 'story', 'summary', 'tagline', 'actors',
       'wins_nominations', 'release_date', 'country'],
      dtype='object')

In [99]:
movies.head()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date,country
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA),India
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India),India
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA),India
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA),India
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India),India

In [100]:
movies.isnull().sum()

title_x                0
imdb_id                0
poster_path          103
wiki_link              0
title_y                0
original_title         0
is_adult               0
year_of_release        0
runtime                0
genres                 0
imdb_rating            0
imdb_votes             0
story                 20
summary                0
tagline             1072
actors                 5
wins_nominations     922
release_date         107
country                0
dtype: int64

In [102]:
movies.dropna(inplace=True)

In [104]:
movies.isnull().sum()

title_x             0
imdb_id             0
poster_path         0
wiki_link           0
title_y             0
original_title      0
is_adult            0
year_of_release     0
runtime             0
genres              0
imdb_rating         0
imdb_votes          0
story               0
summary             0
tagline             0
actors              0
wins_nominations    0
release_date        0
country             0
dtype: int64

In [105]:
#astype:which is used to chnage the datatype of column
ipl.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [107]:
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    object
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: float64(1), int64(1), object(18)
memory usage: 148.6+ KB

In [115]:
ipl['ID']=ipl['ID'].astype('int32')
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int32
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    object
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: float64(1), int32(1), object(18)
memory usage: 144.9+ KB

In [116]:
ipl['Season']=ipl['Season'].astype('category')

In [117]:
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int32
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    category
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: category(1), float64(1), int32(1), object(17)
memory usage: 139.0+ KB