In [1]:
import pandas as pd
import numpy as np

In [3]:
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.compose import ColumnTransformer

In [6]:
df=pd.read_csv("C:/Users/Dell/Downloads/train.csv")[['Age','Fare','SibSp','Parch','Survived']]

In [7]:
df.dropna(inplace=True)

In [8]:
df.head()

    Age     Fare  SibSp  Parch  Survived
0  22.0   7.2500      1      0         0
1  38.0  71.2833      1      0         1
2  26.0   7.9250      0      0         1
3  35.0  53.1000      1      0         1
4  35.0   8.0500      0      0         0

In [9]:
df.isnull().sum()

Age         0
Fare        0
SibSp       0
Parch       0
Survived    0
dtype: int64

In [11]:
df['Family']=df['SibSp']+df['Parch']

In [12]:
df.head()

    Age     Fare  SibSp  Parch  Survived  Family
0  22.0   7.2500      1      0         0       1
1  38.0  71.2833      1      0         1       1
2  26.0   7.9250      0      0         1       0
3  35.0  53.1000      1      0         1       1
4  35.0   8.0500      0      0         0       0

In [13]:
df.drop(columns=['SibSp','Parch'],inplace=True)

In [14]:
df.head()

    Age     Fare  Survived  Family
0  22.0   7.2500         0       1
1  38.0  71.2833         1       1
2  26.0   7.9250         1       0
3  35.0  53.1000         1       1
4  35.0   8.0500         0       0

In [15]:
x=df.drop(columns=['Survived'])
y=df['Survived']

In [16]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [18]:
#without binarization
clf=DecisionTreeClassifier()
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
accuracy_score(y_test,y_pred)

0.6465116279069767

In [20]:
#apply binarization
from sklearn.preprocessing import Binarizer

In [24]:
trf=ColumnTransformer([('bin',Binarizer(copy=False),['Family'])],remainder='passthrough')

In [25]:
X_train_trf=trf.fit_transform(X_train)
X_test_trf=trf.transform(X_test)

In [27]:
pd.DataFrame(X_train_trf,columns=['Family','Age','Fare'])

     Family   Age      Fare
0       0.0  21.0    8.0500
1       1.0   5.0   27.7500
2       0.0  28.5    7.2292
3       0.0  59.0    7.2500
4       0.0  40.0   31.0000
..      ...   ...       ...
494     1.0  46.0   61.1750
495     0.0  25.0   13.0000
496     0.0  41.0  134.5000
497     1.0  33.0   20.5250
498     0.0  33.0    7.8958

[499 rows x 3 columns]