In [3]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [9]:
headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
webpage=requests.get('https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav',headers=headers).text

In [10]:
soup=BeautifulSoup(webpage,'lxml')#lxml because of this we can traverse easily in html code

print(soup.prettify())#it is used to format the html code

# Names Of All company

In [26]:
for i in soup.findAll('h2'):
    print(i.text.strip())

Companies in India
TCS
Accenture
Wipro
Cognizant
Capgemini
HDFC Bank
Infosys
HCLTech
ICICI Bank
Tech Mahindra
Genpact
TP
Axis Bank
Jio
Concentrix Corporation
Amazon
Reliance Retail
iEnergizer
LTM Limited
HDB Financial Services
Popular Collections by Industries
Popular Collections by Cities
Popular Collections by Roles

In [27]:
len(soup.findAll('h2'))

24

# For Finding Rating

In [28]:
for i in soup.findAll('div',class_="rating_text"):
  print(i.text.strip())

3.3
3.7
3.6
3.7
3.6
3.8
3.5
3.4
4.0
3.3
3.6
3.9
3.6
4.4
3.5
3.9
3.9
4.5
3.6
3.9

In [29]:
len(soup.findAll('div',class_="rating_text"))

20

In [30]:
company=soup.find_all('div',class_='companyCardWrapper')

In [31]:
len(company)

20

In [33]:
name = []
rating = []
reviews = []
salaries = []
interviews = []
jobs = []

for i in company:
    name.append(i.find('h2').text.strip())
    rating.append(i.find('div', class_='rating_text').text.strip())
    
    
    actions = i.find_all('span', class_='companyCardWrapper__ActionCount')
    
    reviews.append(actions[0].text.strip())
    salaries.append(actions[1].text.strip())
    interviews.append(actions[2].text.strip())
    jobs.append(actions[3].text.strip())

df = pd.DataFrame({
    'name': name,
    'rating': rating,
    'reviews': reviews,
    'salaries': salaries,
    'interviews': interviews,
    'jobs': jobs
})

In [34]:
name

['TCS',
 'Accenture',
 'Wipro',
 'Cognizant',
 'Capgemini',
 'HDFC Bank',
 'Infosys',
 'HCLTech',
 'ICICI Bank',
 'Tech Mahindra',
 'Genpact',
 'TP',
 'Axis Bank',
 'Jio',
 'Concentrix Corporation',
 'Amazon',
 'Reliance Retail',
 'iEnergizer',
 'LTM Limited',
 'HDB Financial Services']

In [39]:
jobs

['5k',
 '14.9k',
 '3',
 '919',
 '2.1k',
 '544',
 '3.5k',
 '282',
 '17',
 '803',
 '523',
 '1.5k',
 '222',
 '--',
 '29',
 '85',
 '89',
 '76',
 '748',
 '4']

In [40]:
df.sample(5)

               name rating reviews salaries interviews jobs
16  Reliance Retail    3.9   28.1k    74.9k         2k   89
3         Cognizant    3.7   63.4k     6.1L       6.6k  919
5         HDFC Bank    3.8   54.7k     1.5L       3.2k  544
18      LTM Limited    3.6   27.4k       2L       3.5k  748
17       iEnergizer    4.5   27.9k    25.2k       1.7k   76

In [41]:
df.head()

        name rating reviews salaries interviews   jobs
0        TCS    3.3    1.2L    10.4L      11.4k     5k
1  Accenture    3.7   76.1k     7.3L       9.6k  14.9k
2      Wipro    3.6   67.1k     4.9L         7k      3
3  Cognizant    3.7   63.4k     6.1L       6.6k    919
4  Capgemini    3.6   55.5k       5L       5.7k   2.1k

In [42]:
df.shape

(20, 6)