In [2]:
import pandas as pd
import requests

In [3]:
response = requests.get('https://movies-ratings2.p.rapidapi.com/ratings?id=tt0111161&rapidapi-key=a718fa1fb0mshd32170de796a7b8p1c3327jsn999e6261e8a4')

In [4]:
response

In [5]:
df = pd.DataFrame([response.json()['media']])

In [6]:
df

,backdrop_path,budget,genres,homepage,id,imdb_id,origin_country,original_language,original_title,overview,...,revenue,runtime,spoken_languages,status,tagline,title,video,external_ids,director,media_type
0,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,25000000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",,278,tt0111161,[US],en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,...,28341469,142,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Fear can hold you prisoner. Hope can set you f...,The Shawshank Redemption,False,"{'imdb_id': 'tt0111161', 'wikidata_id': 'Q1722...",Frank Darabont,movie

In [7]:
df_selected = df[['title', 'release_date', 'runtime', 'budget', 'popularity']]

In [8]:
df_selected

                      title release_date  runtime    budget  popularity
0  The Shawshank Redemption   1994-09-23      142  25000000     173.309

In [9]:
df_selected.shape

(1, 5)

In [10]:
df.head()

,backdrop_path,budget,genres,homepage,id,imdb_id,origin_country,original_language,original_title,overview,...,revenue,runtime,spoken_languages,status,tagline,title,video,external_ids,director,media_type
0,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,25000000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",,278,tt0111161,[US],en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,...,28341469,142,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Fear can hold you prisoner. Hope can set you f...,The Shawshank Redemption,False,"{'imdb_id': 'tt0111161', 'wikidata_id': 'Q1722...",Frank Darabont,movie